### ISSUE TITLE
Enzyme Internal Error: unknown node with tag 14

### ISSUE THREAD

**Issue by DMShamonov** [airbnb/enzyme#1604]
### Current behavior
After update `React` to 16.3.0 version and use `forwardRef`, my tests is broken.

Component that uses `forwardRef` now exports as:
```
export default forwardRef((props, ref) => (
  <Input {...props} forwardedRef={ref} />
));
```

and test is:
```
test('with `id` prop', () => {
    const output = shallow(<Input id={id} />);

    expect(renderToJson(output)).toMatchSnapshot();
  });
``` 

throw error is: `Invariant Violation: ReactShallowRenderer render(): Shallow rendering works only with custom components, but the provided element type was 'object'.`

But if I use `render` method this error doesn't happened. 

When I use `mount` method with test is:
```
test('value state is changed', () => {
    const value = 'New value';
    const wrapper = shallow(<Input />);

    wrapper.setProps({ value });
    expect(wrapper.state().value).toEqual(value);
  });
```

I catch error is: `Enzyme Internal Error: unknown node with tag 14`

#### API

- [x] shallow
- [x] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           | 3.3.0
| React            |  16.3.0

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by koba04** [comment]
This might be solved by https://github.com/airbnb/enzyme/pull/1592

**Comment by petegleeson** [comment]
@koba04 I was having the same problem, it is fixed by #1592

**Comment by Hypnosphi** [comment]
My workaround is this:

```
// WrappedInput.js
export const WrappedInput = (props, ref) => <Input {...props} forwardedRef={ref} />

export default React.forwardRef(WrappedInput)
```

```
// WrappedInput.test.js
import {WrappedInput} from './WrappedInput'

test('with `id` prop', () => {
  const output = shallow(WrappedInput({id}));

  expect(renderToJson(output)).toMatchSnapshot();
});
```

**Comment by joepuzzo** [comment]
You could add a patch as specified in this issue https://github.com/airbnb/enzyme/pull/1513

**Comment by FezVrasta** [comment]
@KevinGrandon I'm trying your package but I still get the same error, are you sure it ships the patch needed for the forwardRef feature?

**Comment by Hypnosphi** [comment]
@KevinGrandon Looks like your package doesn't include a fix for ForwardRef

**Comment by ljharb** [comment]
There's no need for a separate package; everything in this repo is now published.

#1592 will fix it once merged and released.

**Comment by DMShamonov** [comment]
@ljharb With `mount` method I still catching this error (` Enzyme Internal Error: unknown node with tag 14`)

**Comment by ljharb** [comment]
It’s not released yet, i just merged it an hour ago.

**Comment by sevketufuk** [comment]
so 3.4.2 should solve this problem? I'm using 3.4.2 and I still got the same error.

**Comment by ljharb** [comment]
No, it should not. This is a new feature, so it would be included in v3.5.0.

**Comment by leobetosouza** [comment]
@ljharb any prevision to v3.50 release?

**Comment by ljharb** [comment]
Like every release, after it’s ready, and when time permits.

It hasn’t even been a full day yet. I do sleep, in case that isn’t apparent.

**Comment by DBjelovuk** [comment]
I'm on 3.10.0. Error persists...
