### ISSUE TITLE
Getting a `TypeError` when rendering with mount()

### ISSUE THREAD

**Issue by lezoudali** [airbnb/enzyme#908]
I'm really not sure why I'm getting the following error when trying to use `mount()` to simulate a click event with a child component. Am i missing something? 

```
  ● <Navigation /> › should open the drawer menu

    TypeError: 'Symbol(Symbol.toPrimitive)' returned for property 'Symbol(Symbol.toPrimitive)' of object '[object Object]' is not a function
      
      at Object.setValueForProperty (node_modules/react-dom/lib/DOMPropertyOperations.js:142:47)

      ...

      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Object.<anonymous> (src/components/navigation/__tests__/navigation.test.js:8:39)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

This is my test code

```
import React from 'react';
import { shallow, mount } from 'enzyme';
import Navigation from '..';

describe('<Navigation />', () => {
  it('should open the drawer menu', () => {
    const component = mount(<Navigation />);

    expect(component.find('.drawer.is-visible')).toHaveLength(0);
    component.find('.nav-menu-btn').simulate('click');
    expect(component.find('.drawer.is-visible')).toHaveLength(1);
  });
})
```

This is the code I'm testing:
```
import React from 'react';
import NavBar from './navbar';
import Drawer from './drawer';

class Navigation extends React.Component {
  constructor() {
    super();

    this.state = {
      isDrawerVisible: false,
    };

    this.toggleIsDrawerVisible = this.toggleIsDrawerVisible.bind(this);
  }

  toggleIsDrawerVisible() {
    this.setState({
      isDrawerVisible: !this.state.isDrawerVisible,
    });
  }

  render() {
    return (
      <div>
        <NavBar onMenuClick={this.toggleIsDrawerVisible} />
        <Drawer isVisible={this.state.isDrawerVisible} />
      </div>
    );
  }
}

export default Navigation;
```

Thank you, this is my first time using enzyme.

**Comment by lezoudali** [comment]
using `enzyme 2.8.2`, `jest 19.0.2`, and `react 15.5.4`

**Comment by ljharb** [comment]
What node or browser version are you running this in? Are you polyfilling `Symbol` somehow (like with core-js/babel-polyfill)?

**Comment by lezoudali** [comment]
I'm using node v7.4.0 and I don't think I'm polyfilling `Symbol`. it seems to work with just with `mount(<div></div>)`, so i thought the issue might be with my component. 

here's my code for the `NavBar` and `Drawer`, they work fine but maybe i'm missing something?
```
import React from 'react';
import PropTypes from 'prop-types';
import MediaQuery from 'react-responsive';
import { menuIcon, percoWhite } from '../../../assets';
import './styles.scss';


const NavBar = props => (
  <div className="main-header">
    <nav className="main-header-nav">
      <div className="nav-section nav-section-left">
        <img
          className="nav-section__item nav-menu-btn"
          onClick={props.onMenuClick} src={menuIcon}
          alt=""
        />
        <a href="#" className="nav-section__item nav-logo">
          <img src={percoWhite} alt="Percolate" />
        </a>
      </div>

      <MediaQuery minWidth={750}>
        <div className="nav-section nav-section-right">
          <a href="#" className="nav-section__item"><span>Barista</span></a>
          <a href="#" className="nav-section__item"><span>Glossary</span></a>
          <a href="#" className="nav-section__item"><span>Organization</span></a>
          <a href="#" className="nav-section__item"><span>Resources</span></a>
        </div>
      </MediaQuery>
    </nav>
  </div>
);

NavBar.propTypes = {
  onMenuClick: PropTypes.func.isRequired,
};

export default NavBar;
```

```
import React from 'react';
import PropTypes from 'prop-types';
import { exitIcon, profileImage } from '../../../assets';
import './styles.scss';

const Drawer = ({ isVisible }) =>
  <div className={`drawer${isVisible ? ' is-visible' : ''}`}>
    <header className="drawer-header">
      <a href="#">
        <img className="drawer-profile-img" src={profileImage} alt="" />
      </a>
    </header>

    <nav className="drawer-nav">
      <a href="#" className="drawer-nav__item">Admin</a>
      <a href="#" className="drawer-nav__item">Files</a>
      <div className="drawer-separator" />
      <a href="#" className="drawer-nav__item">Organization</a>
      <a href="#" className="drawer-nav__item">Glossary</a>
      <a href="#" className="drawer-nav__item">Resource</a>
      <div className="drawer-separator" />
      <a href="#" className="drawer-nav__item">API Documentation</a>
      <div className="drawer-separator" />
      <a href="#" className="drawer-nav__item logout">
        <span>Logout</span>
        <img className="exit-icon" src={exitIcon} alt="" />
      </a>
    </nav>
  </div>;

Drawer.propTypes = {
  isVisible: PropTypes.bool.isRequired,
};

export default Drawer;
```

**Comment by lezoudali** [comment]
@ljharb so the issue somehow got fixed by itself the next after updating my dependencies, sorry to bother. I'm all good 😄

**Comment by aleksandarcrvc** [comment]
@lezoudali could you please tell me exactly how did you solve this because I am facing same issue. Did you move some of npm modules from devDependencies to dependencies?

**Comment by denieler** [comment]
@aleksandarcrvc it seems it connected to 

```
"babel": {
    "presets": []
}
```

configuration. Try to use `stage-0`.

**Comment by PainKKKiller** [comment]
I have babelrc with configuration to use stage-0, and I still have this error with jest

**Comment by denieler** [comment]
@PainKKKiller you can try `babel-preset-env` and if it will fix your problems downgrade to one of `stage-x` that will work for you.

**Comment by patoncrispy** [comment]
Does anyone know what causes this issue?

**Comment by grylance** [comment]
I solved this issue by mocking my `.less` imports: `jest.mock('./Styles.less', () => ({}))`
